<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Version>1.8.9</Version>
    <Description>

    </Description>
    <LangVersion>preview</LangVersion>
    <Platforms>AnyCPU;x86</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!--<ApplicationIcon />-->
    <OutputType>Library</OutputType>
    <!--<StartupObject />-->
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="GeometryUtility\FirstCoorSystem.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="GeometryUtility\FirstCoorSystem.cs" />
  </ItemGroup>

  <ItemGroup>
    <!--<PackageReference Include="AForge.Imaging" Version="2.2.5" />
    <PackageReference Include="AForge.Video.DirectShow" Version="2.2.5" />-->
    <PackageReference Include="AForge.Video.DirectShow" Version="2.2.5" />
    <PackageReference Include="ConfigureAwaitChecker.Analyzer" Version="5.0.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Humanizer.Core" Version="2.14.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.3" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net45" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Toolkit.Diagnostics" Version="7.1.2" />
    <PackageReference Include="netDxf" Version="2023.11.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NModbus.Serial" Version="3.0.81" />
    <PackageReference Include="NModbus.SerialPortStream" Version="3.0.81" />
    <PackageReference Include="propertychanged.fody" Version="4.1.0" />
    <PackageReference Include="System.Reactive" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MachineClassLibrary.Core\MachineClassLibrary.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AdvMotAPI">
      <HintPath>..\..\..\..\..\Program Files (x86)\Advantech\Common Motion\Public\AdvMotAPI.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
